### ISSUE TITLE
HW7 incorrect constraint

### ISSUE THREAD

**Issue by BitNide** [rickstaa/MBD_B#2]
Hey man, When you look at the Y values you will find a sudden jump from your initial conditions.
When simulating the motion using:

y = q_RK4.';

g = figure(1);
filename = 'testAnimated.gif';
for n=1:length(y)-1
    figure(1)
    line([0, 0.2*cos(y(1,n))],[0.3, 0.3+0.2*sin(y(1,n))])
    line([0, 0.7*cos(y(2,n))],[0, 0.7*sin(y(2,n))])
    line([0.7*cos(y(2,n)), 0.7*cos(y(2,n))+ cos(y(3,n))*0.6],[0.7*sin(y(2,n)), 0.7*sin(y(2,n))+sin(y(3,n))*0.6])
    xlim([-1.5 1])
    ylim([0 1])
    drawnow
    frame = getframe(g);
    im = frame2im(frame);
    [imind,cm] = rgb2ind(im,256);
    if n == 1 
          imwrite(imind,cm,filename,'gif', 'Loopcount',inf); 
    else 
          imwrite(imind,cm,filename,'gif','WriteMode','append'); 
    end 
    clf
end

![incorrectc](https://user-images.githubusercontent.com/40611662/41935749-13d6e21c-798b-11e8-9008-34da356bf0b2.gif)

I found that you incorrectly formulated the constraint relation between phi4 and point A.
you are currently using:
-parms.O4A*cos(phi4)+parms.O2A*cos(phi2)
First off this does not amount to a total of 0. Secondly it fails to acknowledge the vertical shift of the slider and thus lenght variation of O4A.

I replaced it with:
-y3*cos(phi4)+x3*sin(phi4)  

This correctly incorporates the relation both horizontal and vertical and will provide better results:
![testanimated](https://user-images.githubusercontent.com/40611662/41935656-b551c6a8-798a-11e8-9547-83779af9c2ec.gif)

**Comment by rickstaa** [comment]
Thanks a lot for pointing that out. I was just looking for what I did wrong at this very moment!

**Comment by rickstaa** [comment]
Be aware that there might be another small error in the code since two of the plots are wrong. I will look at your comment and see if it also fixed the wrong plots tomorrow.

**Comment by rickstaa** [comment]
I think it will fix the problem I had thanks! I will push the new version tomorrow!

**Comment by rickstaa** [comment]
If you see another error let me know I checked every script up till 7 still need to check 8 9 and 10.

**Comment by BitNide** [comment]
if you also remove the gravity the plots should also be good 👍

**Comment by rickstaa** [comment]
It is indeed working! I just pushed the new version including a modification of your animation script to the GitHub. Thanks for pointing out my error!
